### ISSUE TITLE
Search should be case insensitive

### ISSUE THREAD

**Issue by michaelwschultz** [Chentai-Kao/codemap-public#13]
Feels like this is what I would expect to happen plus is helpful in finding functions named similarly.

**Comment by Chentai-Kao** [comment]
That's a good point, and I should add that to my roadmap. Meanwhile, The new web version of Codemap utilizes the built-in browser search, which is case insensitive.

**Comment by Chentai-Kao** [comment]
@michaelwschultz I've released a new version of Codemap that's loaded in the browser, so now search should be case insensitive. Please try it out at https://codemap.app. Closing this issue.
