### ISSUE TITLE
Strange view

### ISSUE THREAD

**Issue by Fodin** [Chentai-Kao/codemap-public#14]
I have a project about 900 files of js and jsx. In codemap it renders like this:
![image](https://user-images.githubusercontent.com/15780894/160169013-a83c08e6-5efc-4a64-908c-25ad31f43983.png)

**Comment by Chentai-Kao** [comment]
Hi, is it possible that it reached the limit of **100 functions** under the free plan? There should be some statistics on the bottom left corner that shows how many functions exist in total. Is that count lower than expected?

**Comment by Chentai-Kao** [comment]
@Fodin please try out the new Codemap at https://codemap.app, and please feel free to let me know if it's still confusing. Closing this issue for now.
