### ISSUE TITLE
Python not found. 

### ISSUE THREAD

**Issue by benalex99** [Chentai-Kao/codemap-public#15]
I have multiple versions of python installed, including one that is added to PATH.

Perhaps add a setting to point out the python installation manually?

**Comment by jl1011** [comment]
Hmmm, try: https://stackoverflow.com/questions/65348890/python-was-not-found-run-without-arguments-to-install-from-the-microsoft-store
?

**Comment by Chentai-Kao** [comment]
Codemap currently runs the `python3` from your PATH. That said, there's some issues with finding the right Python runtime, and it's on my roadmap to support configuring the Python path dynamically. Thanks for suggesting that.

**Comment by Chentai-Kao** [comment]
Hi @benalex99 and @jl1011, I've released a new version of Codemap that supports customized Python path. Could you try it out with the new app at https://codemap.app? Thanks.
