### ISSUE TITLE
Apple Silicon Codemap Desktop "is damaged"

### ISSUE THREAD

**Issue by stefanjcollier** [Chentai-Kao/codemap-public#19]
Hi,

I'd love to run this but

It seems the download for apple silicon is broken. I get the following error upon opening the application:

> “Codemap Desktop” is damaged and can’t be opened. You should move it to the Bin.

## Steps to reproduce

1. Go to https://codemap.app/dashboard
2. Click pick a project
3. Pick Parser: Ruby
4. Press the download button "Download Codemap Desktop 1.6.1"
5. Fromt the dropdown select "Mac (Apple Silicon)"
6. \* file downloads * 
7. Click download, it opens the a desktop window to drag the Application -> Applications
8. Drag application in applications
9. \* takes ~ 5 seconds to 'install' *
10. (In Applications) double click the application and 💥 the error:

![image](https://github.com/Chentai-Kao/codemap-public/assets/10790166/bfd7418a-e9d7-40ca-9b3e-5a2ac8537363)

## Macbook specs
(aka proof I'm running apple silicon)

![macbook specs](https://github.com/Chentai-Kao/codemap-public/assets/10790166/01f979b7-1255-4858-98da-59cada68d74a)

--- 

Hope this helps. If there's anymore info you would like me to try. Happy to help 😊 

Thanks!

**Comment by ohmygaugh-crypto** [comment]
You need to run this command per the trouble shooting suggestions:

<img width="447" alt="image" src="https://github.com/Chentai-Kao/codemap-public/assets/58447309/83cda228-b9e4-4583-8d89-c2f529c5e626">

Then running the command should result in:
<img width="545" alt="image" src="https://github.com/Chentai-Kao/codemap-public/assets/58447309/599de41d-1adb-4186-b518-5fa88850c9b2">

Then it should run:
<img width="548" alt="image" src="https://github.com/Chentai-Kao/codemap-public/assets/58447309/f99854c8-312f-4f97-ab29-b95dadc2fe74">

**Comment by Chentai-Kao** [comment]
Sorry for the late reply. Glad @ohmygaugh-crypto provided the exact troubleshooting steps.
To recap the troubleshooting steps (outlined in the Codemap when you download the app), Mac warns about installing 3rd party apps downloaded from the Internet, and mark the app with a quarantine flag. Removing the flag will make the app work just fine, by running `xattr -c '/Applications/Codemap Desktop.app'`.
