### ISSUE TITLE
Can't actually paste the premium token into the box

### ISSUE THREAD

**Issue by jimtje** [Chentai-Kao/codemap-public#4]
Hey there. Always happy to support independent software development, but it the box where the code is supposed to be pasted into requires the code to be typed in.

**Comment by Chentai-Kao** [comment]
Thanks for reporting this. Let me rebuild Codemap with the latest Mac OS and see if that fixes the issue.

**Comment by Chentai-Kao** [comment]
With the new version of Codemap, pasting the premium token is no longer necessary. Please feel free to try out the new version at https://codemap.app and let me know if any other issue occurs. Closing this issue as fixed.
