### ISSUE TITLE
Misses function calls

### ISSUE THREAD

**Issue by ctwardy** [Chentai-Kao/codemap-public#5]
Note this function calls `clean_colnames` and `drop_errors`:
```python
def clean_and_augment_data(data: pd.DataFrame,
                           categories: pd.DataFrame,
                           dropcols: List[str] = ['reports', 'category_counts', 'countryCode', 'ipVersion']) \
        -> pd.DataFrame:
    """Clean up the column names, extract category counts, drop interim fields, and add the date of the pull"""
    global today

    clean_colnames(data)
    drop_errors(data)
```

However, codemap shows them disconnected:
![image](https://user-images.githubusercontent.com/925782/110493646-d032d300-80c0-11eb-969d-36b6e0318894.png)

They are in the same file.

The calling function calls 7 other functions, all defined in the same file.
* It shows three that appear on the RHS of an assignment `=` operator.
![image](https://user-images.githubusercontent.com/925782/110493942-17b95f00-80c1-11eb-8021-a4a2cb6bd514.png)
* It misses the two above, and:
  * `rename_cats`, which also appears without assignment.
  * `extract_category_counts(row)`, on the RHS but in a lambda.  

I could rewrite these to use assignment, but it's a pandas project and I'm using `inline=True` in the hope that will be faster and use less memory.

Besides, being a function call inside another function should be pretty easy to track.

**Comment by Chentai-Kao** [comment]
Hi @ctwardy, to make sure I understand the bug:

- `value = fun()` it works when the function call is on the RHS
- `fun()` does not work if function call is on the LHS
- `lambda x: fun(x)` also does not work if function call is in a Lambda function

Is that correct?

**Comment by ctwardy** [comment]
Yes. I haven't tried since reporting that bug, but that was the behavior.  So a function `doThreeThings()` with calls `doThis(); doThat(); doTheOtherThing();` would generate no links.  

_Aside: I've since learned that `inline=True` is deprecated in part because it suggests memory savings that aren't realized. But still._

**Comment by Chentai-Kao** [comment]
Hi @ctwardy, I've released a new version that fixed this issue. Please see the screenshot below, with the sample code on the left side of the screenshot. Feel free to visit https://codemap.app and try it out :)

<img width="1464" alt="Screenshot 2022-12-31 at 15 02 10" src="https://user-images.githubusercontent.com/1172768/210307281-1c094b3f-172e-424f-8859-e0b1715e265f.png">
