### ISSUE TITLE
How to handle `lambda`?

### ISSUE THREAD

**Issue by ctwardy** [Chentai-Kao/codemap-public#6]
Suppose `calling_fun()` calls `my_fun()` using a lambda, like so:
```python
df.apply(lambda row: my_fun(row), axis=1)
```

Options
1. Just show `calling_fun` ➛ `my_fun`.
2. Show `calling_fun` ➛ λ ➛ `my_fun`.

Right now it may miss `my_fun` entirely (ticket filed).  I'd suggest Option 2 is better. That said, you probably don't want all λ to be the same node!  So you could label the _edge_ instead. Or similar.

**Comment by Chentai-Kao** [comment]
Hi @ctwardy, now lambda functions are handled correctly with the new version of Codemap. Please see the screenshot below, with the sample code on the left side of the screenshot. Feel free to visit https://codemap.app and try it out :)

<img width="1464" alt="Screenshot 2022-12-31 at 15 02 10" src="https://user-images.githubusercontent.com/1172768/210307713-eee3928d-e5b4-4da2-a3fa-96fa95fead68.png">
