### ISSUE TITLE
The application takes forever to load

### ISSUE THREAD

**Issue by Sanjaykrishnamurthy** [Chentai-Kao/codemap-public#7]
After I click on the folder icon in the top left and choose the Python folder, it lists the 3 python files in that particular folder. I click on Visualize and then comes the Discovering files screen where it just hangs indefinitely. 

I am using Windows10, 64 bit with 32GB Ram and I am trying to visualize in Python

**Comment by quantsummaries** [comment]
I'm having the same issue when trying to visualize a Python module.
![codemap_issue](https://user-images.githubusercontent.com/73797703/116481578-75606100-a851-11eb-96cf-28dbf84c2d8a.jpg)

**Comment by jl1011** [comment]
I can confirm this is still an issue :(

**Comment by Chentai-Kao** [comment]
Unsure about the root cause, but a few guesses:
1. Is `python3` available in the PATH?
2. Does Codemap has **write permission** to the file system (to write an output file)?

**Comment by Chentai-Kao** [comment]
Hi @Sanjaykrishnamurthy @quantsummaries @jl1011 I've released a new version of Codemap that's better at displaying the error message in case there's an error, and customized Python path depending on your Python installation. Could you try it out at https://codemap.app and let me know if this is still an issue? Thanks.
