### ISSUE TITLE
How to point it to my python env and set interpriter (conda, windows)?

### ISSUE THREAD

**Issue by OlegJakushkin** [Chentai-Kao/codemap-public#9]
How to point it to my python env and set interpreter?

` Uncaught (in promise) Python was not found; run without arguments to install from the Microsoft Stor`

**Comment by jl1011** [comment]
Did you ever find out the answer? :(

**Comment by Chentai-Kao** [comment]
Thanks @jl1011.
Was the above solution working for you, @OlegJakushkin ?

**Comment by Chentai-Kao** [comment]
@OlegJakushkin I've released a new version of Codemap that supports customized Python path and shouldn't throw this error anymore. Could you try it out at https://codemap.app? Thanks.
